version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - run: apt-get update && apt-get install -y libgmp-dev curl

      - checkout

      - run: |
          mkdir -p ~/.local/bin
          curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

      - run: |
          export PATH=$HOME/.local/bin:$PATH
          stack --no-terminal --install-ghc test --only-dependencies

      - run: |
          export PATH=$HOME/.local/bin:$PATH
          stack --no-terminal test --haddock --no-haddock-deps
